name: TEMP
id: TEMP
imports:
- linkml:types
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
  TEMP:
    prefix_prefix: TEMP
    prefix_reference: http://example.org/TEMP/
  sdo:
    prefix_prefix: sdo
    prefix_reference: http://example.org/sdo/
  wikidata:
    prefix_prefix: wikidata
    prefix_reference: http://www.wikidata.org/entity/
default_prefix: TEMP
default_range: string
subsets:
  b:
    name: b
  a:
    name: a
slots:
  id:
    name: id
    exact_mappings:
    - sdo:identifier
    description: any identifier
    from_schema: TEMP
    multivalued: false
    identifier: true
    range: string
    required: true
  description:
    name: description
    exact_mappings:
    - sdo:description
    description: a textual description
    from_schema: TEMP
    multivalued: false
    range: string
    required: false
  name:
    name: name
    from_schema: TEMP
  age:
    name: age
    from_schema: TEMP
  gender:
    name: gender
    from_schema: TEMP
  has medical history:
    name: has medical history
    from_schema: TEMP
classes:
  Person:
    name: Person
    exact_mappings:
    - sdo:Person
    - wikidata:Q215627
    description: a person,living or dead
    from_schema: TEMP
    status: release
    slots:
    - id
    - name
    - age
    - gender
    - has medical history
    slot_usage:
      id:
        name: id
        exact_mappings:
        - sdo:identifier
        description: identifier for a person
        multivalued: false
        identifier: true
        range: string
        required: true
      name:
        name: name
        exact_mappings:
        - sdo:name
        description: full name
        multivalued: false
        range: string
        required: true
      age:
        name: age
        description: age in years
        multivalued: false
        range: decimal
        required: false
      gender:
        name: gender
        description: age in years
        multivalued: false
        range: decimal
        required: false
      has medical history:
        name: has medical history
        description: medical history
        status: testing
        multivalued: true
        range: MedicalEvent
        required: false
  Organization:
    name: Organization
    from_schema: TEMP
    slots:
    - name
    slot_usage:
      name:
        name: name
        exact_mappings:
        - sdo:name
        description: full name
        multivalued: false
        range: string
        required: true
  Event:
    name: Event
    exact_mappings:
    - wikidata:Q1656682
    description: grouping class for events
    in_subset:
    - a
    from_schema: TEMP
    status: release
  MedicalEvent:
    name: MedicalEvent
    description: a medical encounter
    in_subset:
    - b
    from_schema: TEMP
    is_a: Event
    status: testing
  ForProfit:
    name: ForProfit
    from_schema: TEMP
    is_a: Organization
  NonProfit:
    name: NonProfit
    exact_mappings:
    - wikidata:Q163740
    from_schema: TEMP
    is_a: Organization
